branches:
  only:
  - master
  - beta
  - release
  - publish-to-s3-on-tags
  # release branches
  - /^(?:release|lts)-\d+-\d+$/
  # npm version tags
  - /^v\d+\.\d+\.\d+/

language: node_js
node_js:
  - "10"

addons:
  firefox: "latest"

matrix:
  fast_finish: true

cache:
  yarn: true

stages:
  - name: deploy
    if: type IN (push)

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

  # install the most recent `npm version`
  # used when publishing to build a properly packed tarball
  - npm i -g npm

install:
  - yarn install --frozen-lockfile --non-interactive

jobs:
  include:
    - stage: deploy
      env:
      - PUBLISH=true
      script:
        - "./bin/publish_builds"
