branches:
  only:
  - master
  - beta
  - release
  - publish-to-s3-on-tags
  # release branches
  - /^(?:release|lts)-\d+-\d+$/
  # npm version tags
  - /^v\d+\.\d+\.\d+/

language: node_js
node_js:
  - "10"

matrix:
  fast_finish: true

cache:
  yarn: true

stages:
  - name: deploy
    if: type IN (push)

jobs:
  include:
    - stage: deploy
      env:
      - PUBLISH=true
      script:
        - "./bin/publish_builds"
