language: node_js
sudo: required
dist: trusty

node_js:
  - "6"

addons:
  firefox: "latest"

cache:
  directories:
  - $HOME/.yarn-cache

before_install:
- |
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start

    sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt-get update -qq
    sudo apt-get install -y -qq yarn
    yarn --version

    # install the most recent `npm version`
    # used when publishing to build a properly packed tarball
    npm i -g npm

install:
- |
    yarn install

env:
  global:
    - DISABLE_SOURCE_MAPS=true
    - BROCCOLI_ENV=production
    - S3_BUCKET_NAME=builds.emberjs.com
  matrix:
    - TEST_SUITE=browserstack
