name: CI Cron

on:
  push:
    branches:
      - master
  #schedule:
   # - cron:  '0 3 * * *' # daily, 3am

jobs:
  push:
    name: Trigger cron build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
         # - master
         # - beta
          - release
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{matrix.branch}}
      - name: 'Placeholder commit'
        run: |
          touch cron.txt
          git config --local user.email 'cron@example.com'
          git config --local user.name 'Ember.js Cron CI'
          git add cron.txt
          git commit -m "Cron $(date +%Y-%m-%d) for ${{matrix.branch}}"
          export SHA=`git rev-parse HEAD`
          echo "::set-env name=SHA::$SHA"

      - name: Push branch
        run: |
          git checkout -B cron-${{matrix.branch}}-${{env.SHA}}
          git push https://${GITHUB_ACTOR}:${{ secrets.PERSONAL_TOKEN }}@github.com/${GITHUB_REPOSITORY} cron-${{matrix.branch}}-${{env.SHA}} --force
      - name: Wait for suite completion
        uses: jitterbit/await-check-suites@v1
        with:
          ref: ${{ env.SHA }}
          appSlugFilter: github-actions
          onlyFirstCheckSuite: true
          timeoutSeconds: 600
      - name: Cleanup
        if: ${{ success() }} || ${{ failure() }}
        run: git push https://${GITHUB_ACTOR}:${{ secrets.PERSONAL_TOKEN}}@github.com/${GITHUB_REPOSITORY} --delete cron-${{matrix.branch}}-${{env.SHA}}
