name: CI Cron

on:
  push:
    branches:
      - master
  #schedule:
   # - cron:  '0 3 * * *' # daily, 3am

jobs:
  push:
    name: Trigger cron build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - beta
          - release
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{matrix.branch}}
      - name: 'Placeholder commit'
        run: |
          touch cron.txt
          git config --local user.email 'cron@example.com'
          git config --local user.name 'Ember.js Cron CI'
          git add cron.txt
          git commit -m 'Kick off cron on "$(date +%Y-%m-%d)" run of CI for ${{matrix.branch}}'
          export SHA=`git rev-parse HEAD`
          echo "::set-env name=SHA::$SHA"

      - name: Push branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: cron-${{matrix.branch}}
          force: true
          github_token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Wait for suite completion
        uses: jitterbit/await-check-suites@v1
        with:
          ref: ${{ env.SHA }}
          appSlugFilter: github-actions
          onlyFirstCheckSuite: true
          timeoutSeconds: 600
      - name: Cleanup
        run: git push https://${GITHUB_ACTOR}:${{ secrets.PERSONAL_TOKEN}}@github.com/${GITHUB_REPOSITORY} --delete cron-${{matrix.branch}}
