name: Cron

on:
  push:
    branches:
      - master
  #schedule:
   # - cron:  '0 3 * * *' # daily, 3am

jobs:
  push:
    name: Trigger cron build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - beta
          - release
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{matrix.branch}}
      - name: 'Placeholder commit'
        run: |
          touch cron.txt
          git config --local user.email 'cron@example.com'
          git config -- local user.name 'Ember.js Cron CI'
          git commit -m 'Add commit' -a
      - name: Push branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: cron-${{matrix.branch}}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: List checks
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            let res = await github.checks.listForRef({owner: 'kategengler', repo: 'ember.js', ref: github.sha});
            console.log(JSON.stringify(res, null, 2));
#      - name: Wait for build
#        uses: fountainhead/action-wait-for-check@v1.0.0
#        with:
#          token: ${{ secrets.PERSONAL_TOKEN }}
#          checkName: ci
#          ref: ${{matrix.branch}}
