name: CI

on:
  push:
    branches:
      - master
      - beta
      - release
      # release branches
      - release*
      - lts*
    tags:
      - '*'
  schedule:
    - cron:  '0 3 * * *' # daily, 3am

_actions:
  checkout: &checkout
    uses: actions/checkout@v1

  setup-node: &setup-node
    uses: actions/setup-node@v1
    with:
      node-version: 10.x

  install-deps: &install-deps
    name: install dependencies
    run: yarn install --frozen-lockfile --non-interactive

  default-env: &default-env
    DISABLE_SOURCE_MAPS: true
    BROCCOLI_ENV: production

  download-dist: &download-dist
    uses: actions/download-artifact@v1
      with:
        name: dist
        path: dist

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - *checkout
    - *setup-node
    - *install-deps
    - name: linting
      run: yarn lint

  basic-test:
    name: Debug and Prebuilt (All Tests by Package + Canary Features + Optional Jquery)
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-node
      - *install-deps
      - name: build
        env:
          <<: *default-env
        run: yarn ember build
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      - name: test
        env:
          TEST_SUITE: each-package
        run: yarn test

  browserstack-test:
    name: Browserstack Tests (Safari, Edge, IE11)
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - *checkout
      - *setup-node
      - *install-deps
      - name: build
        env:
          <<: *default-env
          SHOULD_TRANSPILE: true
        run: yarn ember build
      - name: test:browserstack
        env:
          BROWSERSTACK_USERNAME: emberjscoreteam1
          BROWSERSTACK_ACCESS_KEY: YsPxXKcahx9XszyHS2Gr
        run: yarn test:browserstack

  production-test:
    name: Production (All Tests + Canary Features)
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - *checkout
      - *setup-node
      - *install-deps
      - name: build
        env:
          <<: *default-env
        run: yarn ember build -prod
      - name: test
        run: yarn test

  extend-prototypes-test:
    name: Extend Prototypes
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - *checkout
      - *setup-node
      - *install-deps
      - *download-dist
      - name: test
        env:
          TEST_SUITE: extend-prototypes
        run: yarn test

  node-test:
    name: Node.js Tests
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - *checkout
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - *install-deps
      - name: build
        env:
          <<: *default-env
        run: yarn ember build -prod
      - name: test
        run: yarn test:node

  blueprint-test:
    name: Blueprint Tests
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - *checkout
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - *install-deps
      - *download-dist
      - name: test
        run: yarn test:blueprints

  browser-test:
    name: Browser Tests (Firefox)
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - *checkout
      - *setup-node
      - *install-deps
      - *download-dist
      - name: test
        run: yarn ember test -c testem.travis-browsers.js
