name: CI

on:
  push:
    branches:
      - master
      - beta
      - release
      # release branches
      - release*
      - lts*
    tags:
      - '*'
  schedule:
    - cron:  '0 3 * * *' # daily, 3am

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: install dependencies
      run: yarn install --frozen-lockfile --non-interactive
    - name: linting
      run: yarn lint

  basic-test:
    name: Debug and Prebuilt (All Tests by Package + Canary Features + Optional Jquery)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: build
        env:
          DISABLE_SOURCE_MAPS: true
          BROCCOLI_ENV: production
        run: yarn ember build
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      - name: test
        env:
          TEST_SUITE: each-package
        run: yarn test

  browserstack-test:
    name: Browserstack Tests (Safari, Edge, IE11)
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: build
        env:
          DISABLE_SOURCE_MAPS: true
          BROCCOLI_ENV: production
          SHOULD_TRANSPILE: true
        run: yarn ember build
      - name: test:browserstack
        env:
          BROWSERSTACK_USERNAME: emberjscoreteam1
          BROWSERSTACK_ACCESS_KEY: YsPxXKcahx9XszyHS2Gr
        run: yarn test:browserstack

  production-test:
    name: Production (All Tests + Canary Features)
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: build
        env:
          DISABLE_SOURCE_MAPS: true
          BROCCOLI_ENV: production
        run: yarn ember build -prod
      - name: test
        run: yarn test

  production-debug-render-test:
    name: Production (All Tests + Canary Features with Debug Render Tree)
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: build
        env:
          DISABLE_SOURCE_MAPS: true
          BROCCOLI_ENV: production
        run: yarn ember build -prod
      - name: test
        run: yarn test

  extend-prototypes-test:
    name: Extend Prototypes
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - name: test
        env:
          TEST_SUITE: extend-prototypes
        run: yarn test

  node-test:
    name: Node.js Tests
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: build
        env:
          DISABLE_SOURCE_MAPS: true
          BROCCOLI_ENV: production
        run: yarn ember build -prod
      - name: test
        run: yarn test:node

  blueprint-test:
    name: Blueprint Tests
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - name: test
        run: yarn test:blueprints

  browser-test:
    name: Browser Tests (Firefox)
    runs-on: ubuntu-latest
    needs: [basic-test, lint]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - name: test
        run: yarn ember test -c testem.travis-browsers.js

  deploy:
    name: Deploy to npm
    runs-on: ubuntu-latest
#    needs: [basic-test, lint, browserstack-test, production-test, production-debug-render-test, extend-prototypes-test, node-test, blueprint-test, browser-test]
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Test available
        env:
          PUBLISH: true
        run: |
          echo ${GITHUB_REF##*/}
          echo ${GITHUB_EVENT_NAME}
